all: tiles
	# Done
tiles: tiles.cpp
	g++ --std=c++11 -I/usr/local/include/ -L/usr/local/lib -I/opt/local/include -L/opt/local/lib -I/Users/Monika/midifile/include/ -L/Users/Monika/midifile/lib/ -o tiles tiles.cpp -lallegro -lallegro_main -lallegro_primitives -lfluidsynth -lmidifile 
